apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: clone-pipeline
spec:
  params:
    - name: git-url
      type: string
  tasks:
    - name: clone-git
      taskSpec:
        params:
          - name: git-url
            type: string
        steps:
          - name: clone
            image: docker.io/knickkennedy/k8s-tools@sha256:4403945ccbe3c3cd81d3b08d5c79a6a9bd263a798f0edee57b50740f7fef503e
            script: |
              #!/bin/sh

              git clone $(params.git-url) repo
              eval $(yq e '. | to_entries | .[] | "export " + .key + "=" + .value' repo/params.yaml)
              kubectl apply -f repo/pipeline.yaml
              envsubst < repo/pipelinerun.yaml | kubectl apply -f -
      params:
        - name: git-url
          value: $(params.git-url)
